/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shadow (https://sketchfab.com/jaydenelizondo7)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/little-astronaut-2898a4b265d943919ca830e7d746ac13
title: Little-astronaut
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "react-three-fiber";

export function Astronaut(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("astronaut.gltf");
  const { actions } = useAnimations(animations, group);
  const myMesh = React.useRef();
  const openInNewTab = (url) => {
    const newWindow = window.open(url, "_blank", "noopener,noreferrer");
    if (newWindow) newWindow.opener = null;
  };

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.rotation.x += 0.0;
    myMesh.current.rotation.y += 0.0;
    myMesh.current.rotation.z += 0.01;
    myMesh.current.position.x -= 0.015;
    myMesh.current.position.z -= 0;
    if (myMesh.current.position.x < -26) {
      myMesh.current.position.x = props.x;
      myMesh.current.position.y = props.y;
      myMesh.current.position.z = props.z;
    }
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[props.x, props.y, props.z]}
      scale={props.scale}
      rotation={[
        Math.PI * props.rotX,
        Math.PI * props.rotY,
        Math.PI * props.rotZ,
      ]}
    >
      <mesh
        ref={myMesh}
        onClick={() => openInNewTab("http://localhost:3000/about")}
      >
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group
              name="astronautfbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group
                    name="Armature"
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                  >
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_9"
                        geometry={nodes.Object_9.geometry}
                        material={materials.Astronaut}
                        skeleton={nodes.Object_9.skeleton}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("astronaut.gltf");
